### ISSUE TITLE
Doesn't support linuxbrew

### ISSUE THREAD

**Issue by rafee** [go-swagger/homebrew-go-swagger#4]
I tried to use this with linuxbrew. It downloads the Mac binary which doesn't work for obvious reasons.

**Comment by casualjim** [comment]
We publish binaries for all the major linuxes and their package managers. I'm not against a PR but I want to set the expectation that from my POV there is little value in supporting a niche package manager like linuxbrew. So in summary if you want it to work for linuxbrew, send a PR.

**Comment by rafee** [comment]
#5 Corresponding pull request. Works on my machine.
